web:
  ports:
    - "3000:3000"
  volumes:
    - .:/code
  links:
    - db
  environment:
    DB_URL: postgres://postgres@db/open_analytics
  image:
    svevang/open-analytics
db:
  image:
    svevang/open-analytics-db
